### ISSUE TITLE
NO SOCIALSCAN FOUND 1.1.3 ON REQUIREMENTS.TXT

### ISSUE THREAD

**Issue by stuxMY** [kennbroorg/iKy#10]
Could not find a version that satisfies the requirement socialscan==1.1.3 (from -r requirements.txt (line 62)) (from versions: )
No matching distribution found for socialscan==1.1.3 (from -r requirements.txt (line 62))

my machines is ubuntu 18.0.14 lts

**Comment by KennBro** [comment]
What is the python version?
Sorry for the delay, but the project is in gitlab.
Github is just a mirror
