### ISSUE TITLE
celery command not found

### ISSUE THREAD

**Issue by cabiamdos** [kennbroorg/iKy#104]
After installing all the requirements and executing the command I get that celery command not found.
I installing celery other time by typing `pip install celery` but nothing works
![image](https://user-images.githubusercontent.com/82284393/212073088-45613061-6b95-4f1c-b795-22e7e5c155fe.png)

and even done `python3 celery -A celery_worker.celery worker --loglevel=INFO` and nothing works

![image](https://user-images.githubusercontent.com/82284393/212073723-1e3648a3-3482-495c-a793-8af2c790bdac.png)

any ideas?

I am running kali linux on windows subsystem.
Thanks

**Comment by cabiamdos** [comment]
now it seems the celery command is working randomly bud receive 404
![image](https://user-images.githubusercontent.com/82284393/212218075-da0db4ae-23f4-4370-b0be-7736d7bfb942.png)
![image](https://user-images.githubusercontent.com/82284393/212218103-07d6dbe9-f140-470a-a3f5-2254c6429c74.png)

```
python3 app.py -e prod
Starting PROD servers
REDIS serving...
CELERY serving...
Falsk serving...
HTTPD serving...
HTTPD serving...INSIDE
5392:C 13 Jan 2023 02:39:49.676 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
5392:C 13 Jan 2023 02:39:49.676 # Redis version=7.0.7, bits=64, commit=00000000, modified=0, pid=5392, just started
5392:C 13 Jan 2023 02:39:49.676 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
5392:M 13 Jan 2023 02:39:49.676 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
5392:M 13 Jan 2023 02:39:49.676 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
5392:M 13 Jan 2023 02:39:49.676 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
5392:M 13 Jan 2023 02:39:49.676 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.7 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 5392
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

5392:M 13 Jan 2023 02:39:49.677 # Server initialized
5392:M 13 Jan 2023 02:39:49.677 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
5392:M 13 Jan 2023 02:39:49.677 * Loading RDB produced by version 7.0.7
5392:M 13 Jan 2023 02:39:49.677 * RDB age 28 seconds
5392:M 13 Jan 2023 02:39:49.677 * RDB memory usage when created 0.57 Mb
5392:M 13 Jan 2023 02:39:49.677 * Done loading RDB, keys loaded: 0, keys expired: 0.
5392:M 13 Jan 2023 02:39:49.677 * DB loaded from disk: 0.000 seconds
5392:M 13 Jan 2023 02:39:49.677 * Ready to accept connections
 * Serving Flask app 'factories.application' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 
 -------------- celery@LAPTOP- v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.36 2023-01-13 02:39:53
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         factories.application:0x7fe099d38a60
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . modules.darkpass.darkpass_tasks.t_darkpass
  . modules.dorks.dorks_tasks.t_dorks
  . modules.emailrep.emailrep_tasks.t_emailrep
  . modules.fullcontact.fullcontact_tasks.t_fullcontact
  . modules.ghostproject.ghostproject_tasks.t_ghostproject
  . modules.github.github_tasks.t_github
  . modules.gitlab.gitlab_tasks.t_gitlab
  . modules.holehe.holehe_tasks.t_holehe
  . modules.instagram.instagram_tasks.t_instagram
  . modules.keybase.keybase_tasks.t_keybase
  . modules.leaklookup.leaklookup_tasks.t_leaklookup
  . modules.leaks.leaks_tasks.t_leaks
  . modules.linkedin.linkedin_tasks.t_linkedin
  . modules.mastodon.mastodon_tasks.t_mastodon
  . modules.peopledatalabs.peopledatalabs_tasks.t_peopledatalabs
  . modules.reddit.reddit_tasks.t_reddit
  . modules.search.search_tasks.t_search
  . modules.sherlock.sherlock_tasks.t_sherlock
  . modules.skype.skype_tasks.t_skype
  . modules.socialscan.socialscan_tasks.t_socialscan
  . modules.spotify.spotify_tasks.t_spotify
  . modules.tiktok.tiktok_tasks.t_tiktok
  . modules.tinder.tinder_tasks.t_tinder
  . modules.tweetiment.tweetiment_tasks.t_tweetiment
  . modules.twitch.twitch_tasks.t_twitch
  . modules.twitter.twitter_tasks.t_twitter
  . modules.twitter_comparison.twitter_comp_tasks.t_twitter_comp
  . modules.twitter_comparison.twitter_info_tasks.t_twitter_info
  . modules.usersearch.usersearch_tasks.t_usersearch
  . modules.venmo.venmo_tasks.p_venmo
  . modules.venmo.venmo_tasks.t_venmo

[2023-01-13 02:39:53,146: WARNING/MainProcess] /home/kali/.local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-01-13 02:39:53,147: WARNING/MainProcess] /home/kali/.local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-01-13 02:39:53,148: WARNING/MainProcess] /home/kali/.local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_IMPORTS' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the imports instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-01-13 02:39:53,148: WARNING/MainProcess] /home/kali/.local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-01-13 02:39:53,148: WARNING/MainProcess] /home/kali/.local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ACCEPT_CONTENT' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the accept_content instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-01-13 02:39:53,148: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2023-01-13 02:39:54,463: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-01-13 02:39:54,469: INFO/MainProcess] mingle: searching for neighbors
[2023-01-13 02:39:55,496: INFO/MainProcess] mingle: all alone
[2023-01-13 02:39:55,534: INFO/MainProcess] celery@LAPTOP ready.
```

**Comment by KennBro** [comment]
How you did the installation?

In the first part of this issue, celery is not found because it isn't inside the PATH...
Execute in a terminal before run 'python3 app.py -e prod' the following command
```
export PATH=$PATH:$HOME/.local/bin
```
And celery will work

Respect of second part, to test backend you must call to http://127.0.0.1:5000/tasklist because in http://127.0.0.1:5000 there is nothing

**Comment by mriquelmec** [comment]
┌──(kali㉿kali)-[~]
└─$ sudo su                      
[sudo] password for kali: 
┌──(root㉿kali)-[/home/kali]
└─# cd iKy          
                                                      
┌──(root㉿kali)-[/home/kali/iKy]
└─# cd backend
                                                      
┌──(root㉿kali)-[/home/kali/iKy/backend]
└─# ./celery.sh
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/dist-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/dist-packages/celery/loaders/base.py", line 106, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/loaders/base.py", line 106, in <listcomp>
    return [self.import_task_module(m) for m in self.default_modules]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/loaders/base.py", line 86, in import_task_module
    return self.import_from_cwd(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
           
           
           
          What's going on here? It seems like an error when opening celery.sh...help???????????

**Comment by KennBro** [comment]
Don't use python 3.11, for now
