### ISSUE TITLE
(python3 -m pip install -r requirements.txt) when i execute this command the gevent are failed to install

### ISSUE THREAD

**Issue by ghost** [kennbroorg/iKy#11]
Failed building wheel for gevent
Running setup.py clean for gevent
Failed to build gevent
Installing collected packages: gevent, httplib2, lxml, MarkupSafe, murmurhash, nltk, oauth2, oauthlib, pandas, plac, preshed, pycares, PySocks, python-Levenshtein, PyYAML, redis, requests-oauthlib, schedule, blessed, search-engine-parser, tqdm, socialscan, srsly, wasabi, thinc, spacy, tokenize-rt, tweepy, twint, typing, Werkzeug, langdetect, googletrans, vaderSentiment
Running setup.py install for gevent ...

**Comment by KennBro** [comment]
Failed to build gevent -> this is the problem
Please post the entire log.
Sorry the delay, but the principal project is in gitlab

**Comment by fiuderazes** [comment]
I`ve had the same problem, solved by installing separately lxml, greenlet and after these - gevent

**Comment by KennBro** [comment]
Great!!!!
