### ISSUE TITLE
Graphic Error with TASKEXEC

### ISSUE THREAD

**Issue by daniel2005d** [kennbroorg/iKy#110]
After performing a search and the "TaskEXEC" panel is displayed, it does not show anything, however, it collapses and you can see some text or something like that.

![image](https://github.com/kennbroorg/iKy/assets/9272841/faa436c4-c2f9-46a7-93cd-0a5f0303e720)

![image](https://github.com/kennbroorg/iKy/assets/9272841/98deea60-ac18-44a7-a792-d1833a375ce2)

I manage to capture the screen before it finishes collapsing and this is what you see, but when it is expanded you can't see it.

**Comment by KennBro** [comment]
I noticed this only in Chrome. In both Firefox and Brave it works perfectly. I'll see about fixing it soon

**Comment by KennBro** [comment]
Test now
