### ISSUE TITLE
Not Found, Please Help

### ISSUE THREAD

**Issue by cibaliung** [kennbroorg/iKy#116]
Hi IKY Creators, 

The tool you made is truly extraordinary. I am very impressed with your work, but I found a problem, after I installed it according to the Easy Install instructions, and visited http://127.0.0.1:5000/ information in the browser i use is "Not Foud" , please advise.

Thank you

**Comment by KennBro** [comment]
Hi, my name is KennBro

You must follow this [instructions](https://github.com/kennbroorg/iKy#installation)
![Screenshot from 2024-11-28 11-09-07](https://github.com/user-attachments/assets/d20c5a6f-2437-49ca-81a0-d688d7f053d7)

And like it say in the last [url](http://127.0.0.1:4200) in the image, the [url](http://127.0.0.1:4200) is http://127.0.0.1:4200

The url http://127.0.0.1:5000 is the internal API
