### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by shanow7** [kennbroorg/iKy#13]
Hi,
I can't install the celery.sh file, but it installs iKyEasyInstall.sh without a problem, I also have a problem installing python3.7 -m pip install -r requirements.txt (the problem is indicated in red) iKy dialog starts but you cannot add api keys
![obraz](https://user-images.githubusercontent.com/37192410/80871507-4e5a6800-8cad-11ea-9905-0093fc9bbd73.png)

Could you help?

**Comment by KennBro** [comment]
1) What version of python is?
```
python --version
```

**Comment by shanow7** [comment]
3.8.2Temat: Re: [kennbroorg/iKy] install problem (#13)Data: 2020-05-07 4:09Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 
What version of python is?
python --version

**Comment by KennBro** [comment]
First of all, if your python version is 3.8 then you shouldn't put 
```
python3.7 -m pip install -r requirements.txt
```
Because that's running version 3.7

Another thing I would like to know is if you are using Kali 2020, and what method did you use to install iKy?

Finally, if you run 
```
pip install celery
```
And 
```
pip install MarkupSafe
```
What are the outputs?

**Comment by shanow7** [comment]
requirements.txt - dosn't exist./celery.sh - command not foundTemat: Re: [kennbroorg/iKy] install problem (#13)Data: 2020-05-08 0:47Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 
First of all, if your python version is 3.8 then you shouldn't put
python3.7 -m pip install -r requirements.txt

Because that's running version 3.7
Another thing I'd like to know is if you're using Kali 2020
Finally, if you run
pip install celery

And
pip install MarkupSafe

What are the outputs?

**Comment by KennBro** [comment]
I'm sorry, but I don't understand the answer. Try to be a little more neat.
I sent you three questions.

**Comment by shanow7** [comment]
First of all, if your python version is 3.8 then you shouldn't putpython3.7 -m pip install -r requirements.txt
Because that's running version 3.7I install python 3.7 and I couldn't put python3.7 -m pip install -r&nbsp;requirements.txtAnother thing I'd like to know is if you're using Kali 2020yesFinally, if you runpip install celery
Andpip install MarkupSafe
What are the outputs?./celery.sh&nbsp;-&nbsp;command not foundTemat: Re: [kennbroorg/iKy] install problem (#13)Data: 2020-05-08 18:09Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 
I'm sorry, but I don't understand the answer. Try to be a little more neat.
I sent you three questions.

**Comment by KennBro** [comment]
Again, what are the output of 
```
pip install celery
pip install MarkupSafe
```
I'm not interested in the output of 
```
./celery.sh
```
Please, send me an screenshot like the first messages

**Comment by shanow7** [comment]
Temat: Re: [kennbroorg/iKy] install problem (#13)Data: 2020-05-09 1:20Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 
Again, what are the output of
pip install celery
pip install MarkupSafe

I'm not interested in the output of
./celery.sh

Please, send me an screenshot like the first messages
