### ISSUE TITLE
backend not working

### ISSUE THREAD

**Issue by ghost** [kennbroorg/iKy#14]
kali@kali:~/iKy$ cd backend
kali@kali:~/iKy/backend$ ./celery.sh
./celery.sh: line 3: celery: command not found

**Comment by KennBro** [comment]
1) Kali 2020?
2) What method did you use to install iKy?
3) What version of python are you using? (python --version)
3) What is the output of the following command?
```
pip install celery
```

**Comment by ghost** [comment]
1. i use the latest version of kali
2. i just follow the 2019 installation video and manual installation (detailed) of yours
3. (Python 3.8.2)
4. kali@kali:/$ pip install celery
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: celery in /home/kali/.local/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied: vine>=1.3.0 in /home/kali/.local/lib/python3.7/site-packages (from celery) (1.3.0)
Requirement already satisfied: billiard<4.0,>=3.6.0 in /home/kali/.local/lib/python3.7/site-packages (from celery) (3.6.0.0)


Requirement already satisfied: kombu<5.0,>=4.4.0 in /home/kali/.local/lib/python3.7/site-packages (from celery) (4.6.3)
Requirement already satisfied: pytz>dev in /home/kali/.local/lib/python3.7/site-packages (from celery) (2017.3)
Requirement already satisfied: amqp<3.0,>=2.5.0 in /home/kali/.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)

**Comment by KennBro** [comment]
Ok. Kali 2020 has python 2.7 as default 
Send me a screenshot of the following commands
```
python --version
pip install celery
```
Maybe, you have python 3.8.2 installed, but python 2.7 is still active

Please, run 
```
sudo apt-cache search celery
```
And send me the output

**Comment by neiIdyan** [comment]
kali@kali:~$ pip install celery
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)

**Comment by neiIdyan** [comment]
kali@kali:~$ sudo apt-cache search celery
[sudo] password for kali: 
prospector - comprehensive static Python code analyzer
python-amqp-doc - Low-level AMQP client (Documentation)
python-celery-common - async task/job queue based on message passing (common files)
python-celery-doc - async task/job queue based on message passing (Documentation)
python-dask-doc - Minimal task scheduling abstraction documentation
python-django-celery-beat-doc - Database-backed Periodic Tasks (Python3 version)
python-django-celery-results-doc - Celery result backends for Django (Documentation)
python3-amqp - Low-level AMQP client (Python3 version)
python3-celery - async task/job queue based on message passing (Python3 version)
python3-celery-batches - Task class that buffers messages and processes them as a list
python3-dask - Minimal task scheduling abstraction for Python 3
python3-django-celery-beat - Database-backed Periodic Tasks (Documentation)
python3-django-celery-haystack - utilize Celery for automatic haystack index updates (Python3 version)
python3-django-celery-results - Celery result backends for Django (Python3 version)
python3-pylint-celery - Pylint plugin for code using the Celery library (Python3)
python3-pylint-plugin-utils - Utilities and helpers for writing Pylint plugins (Python 3)
python3-socketio - python3 implementation of the Socket.IO realtime client and server
python3-sphinx-celery - Sphinx Celery theme

**Comment by KennBro** [comment]
> kali@kali:~$ pip install celery
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
> Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
> Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
> Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
> Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
> Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)

You forgot the python --version before the pip install celery

**Comment by ghost** [comment]
kali@kali:~$ python --version
Python 2.7.17
kali@kali:~$ pip install celery
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)

**Comment by ghost** [comment]
kali@kali:~$ sudo apt-cache search celery
[sudo] password for kali: 
prospector - comprehensive static Python code analyzer
python-amqp-doc - Low-level AMQP client (Documentation)
python-celery-common - async task/job queue based on message passing (common files)
python-celery-doc - async task/job queue based on message passing (Documentation)
python-dask-doc - Minimal task scheduling abstraction documentation
python-django-celery-beat-doc - Database-backed Periodic Tasks (Python3 version)
python-django-celery-results-doc - Celery result backends for Django (Documentation)
python3-amqp - Low-level AMQP client (Python3 version)
python3-celery - async task/job queue based on message passing (Python3 version)
python3-celery-batches - Task class that buffers messages and processes them as a list
python3-dask - Minimal task scheduling abstraction for Python 3
python3-django-celery-beat - Database-backed Periodic Tasks (Documentation)
python3-django-celery-haystack - utilize Celery for automatic haystack index updates (Python3 version)
python3-django-celery-results - Celery result backends for Django (Python3 version)
python3-pylint-celery - Pylint plugin for code using the Celery library (Python3)
python3-pylint-plugin-utils - Utilities and helpers for writing Pylint plugins (Python 3)
python3-socketio - python3 implementation of the Socket.IO realtime client and server
python3-sphinx-celery - Sphinx Celery theme

**Comment by KennBro** [comment]
> kali@kali:~$ python --version Python 2.7.17 kali@kali:~$ pip install celery
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
> Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
> Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
> Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
> Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
> Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)

Like I said, Kali 2020 has python 2.7 by default.
This is why you can't find celery. You must switch to python 3

**Comment by ghost** [comment]
> > kali@kali:~$ python --version Python 2.7.17 kali@kali:~$ pip install celery
> > Defaulting to user installation because normal site-packages is not writeable
> > Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
> > Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
> > Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
> > Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
> > Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
> > Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)
> 
> Like I said, Kali 2020 has python 2.7 by default

so i will switch to kali 2019? sorry im just a newbie
how to switch to default python 3 
i installed python 3.8 but python2 is still there

**Comment by KennBro** [comment]
> > > kali@kali:~$ python --version Python 2.7.17 kali@kali:~$ pip install celery
> > > Defaulting to user installation because normal site-packages is not writeable
> > > Requirement already satisfied: celery in ./.local/lib/python3.7/site-packages (4.3.0)
> > > Requirement already satisfied: vine>=1.3.0 in ./.local/lib/python3.7/site-packages (from celery) (1.3.0)
> > > Requirement already satisfied: billiard<4.0,>=3.6.0 in ./.local/lib/python3.7/site-packages (from celery) (3.6.0.0)
> > > Requirement already satisfied: pytz>dev in ./.local/lib/python3.7/site-packages (from celery) (2017.3)
> > > Requirement already satisfied: kombu<5.0,>=4.4.0 in ./.local/lib/python3.7/site-packages (from celery) (4.6.3)
> > > Requirement already satisfied: amqp<3.0,>=2.5.0 in ./.local/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.5.0)
> > 
> > 
> > Like I said, Kali 2020 has python 2.7 by default
> 
> so i will switch to kali 2019? sorry im just a newbie

No, no. Give me a second.

**Comment by KennBro** [comment]
Please run this command
```
sudo update-alternatives --config python
```
And send my the output

**Comment by ghost** [comment]
> Please run this command
> 
> ```
> sudo update-alternatives --config python
> ```
> 
> And send my the output

kali@kali:~$ sudo update-alternatives --config python
[sudo] password for kali: 
update-alternatives: error: no alternatives for python

**Comment by KennBro** [comment]
Ok
```
python --version
```
Output
```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3
```
Output
```
python --version
```
Output

**Comment by ghost** [comment]
> Ok
> 
> ```
> python --version
> ```
> 
> Output
> 
> ```
> sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3
> ```
> 
> Output
> 
> ```
> python --version
> ```
> 
> Output

kali@kali:~$ python --version
Python 2.7.17
kali@kali:~$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3
[sudo] password for kali: 
update-alternatives: using /usr/bin/python3 to provide /usr/bin/python (python) in auto mode
kali@kali:~$ python --version
Python 3.8.2
kali@kali:~$ Thanks!

**Comment by neiIdyan** [comment]
kali@kali:~$ cd iKy/
kali@kali:~/iKy$ cd backend
kali@kali:~/iKy/backend$ ./selery.sh
bash: ./selery.sh: No such file or directory
kali@kali:~/iKy/backend$

**Comment by KennBro** [comment]
Ok, wait. Run inside backend directory
```
./celery.sh
```
And if it's work remember run 
```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
```
to get back to python 2

**Comment by KennBro** [comment]
> kali@kali:~$ cd iKy/ kali@kali:~/iKy$ cd backend
> kali@kali:~/iKy/backend$ ./selery.sh bash: ./selery.sh: No such file or directory kali@kali:~/iKy/backend$

./celery.sh # With C

**Comment by ghost** [comment]
> > kali@kali:~$ cd iKy/ kali@kali:~/iKy$ cd backend
> > kali@kali:~/iKy/backend$ ./selery.sh bash: ./selery.sh: No such file or directory kali@kali:~/iKy/backend$
> 
> ./celery.sh # With C

kali@kali:~$ cd iKy/
kali@kali:~/iKy$ cd backend
kali@kali:~/iKy/backend$ ./celery.sh
./celery.sh: line 3: celery: command not found
kali@kali:~/iKy/backend$

**Comment by KennBro** [comment]
Ok. 
```
sudo apt-get install python3-celery
```
And again, inside backend directory
```
./celery.sh
```

**Comment by ghost** [comment]
> Ok.
> 
> ```
> sudo apt-get install python3-celery
> ```
> 
> And again, inside backend directory
> 
> ```
> ./celery.sh
> ```

kali@kali:~/iKy/backend$ ./celery.sh
./celery.sh: line 3: celery: command not found
kali@kali:~/iKy/backend$ ./celery.sh
./celery.sh: line 3: celery: command not found
kali@kali:~/iKy/backend$ 
i install this but still not working sudo apt-get install python3-celery

**Comment by KennBro** [comment]
And python --version is 3.7???

**Comment by ghost** [comment]
> python --version

Python 3.8.2

**Comment by KennBro** [comment]
It must be 3.7.X

**Comment by shanow7** [comment]
iKy/backend$ python --version
Python 3.7.7
/iKy/backend$ sudo apt-get install python3-celery
python3-celery is already the newest version (4.4.2-5).
/iKy/backend$ ./celery.sh
celery: command not found

what next?

**Comment by mubu98** [comment]
> ngx-admin-iKy@2.0.0 start /home/mubu/tools/iKy/frontend
> ng serve

An unhandled exception occurred: Job name "..getProjectMetadata" does not exist.
See "/tmp/ng-BkhoGd/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ngx-admin-iKy@2.0.0 start: `ng serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ngx-admin-iKy@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mubu/.npm/_logs/2020-08-23T23_35_30_715Z-debug.log

**Comment by w17h0u7m3rcy** [comment]
I solved this problem installing the common version:
```
sudo apt-get install python-celery-common

**Comment by Aesir-coder** [comment]
> I solved this problem installing the common version:
> 
> ```
> sudo apt-get install python-celery-common
> ```

Thank you so much for sharing. That is the only command that solved my problem too.
