### ISSUE TITLE
ngx-admin-iKy

### ISSUE THREAD

**Issue by Strannik74** [kennbroorg/iKy#19]
npm WARN ngx-admin-iKy@2.0.0 No description
npm WARN ngx-admin-iKy@2.0.0 No repository field.
-----------------------
❯ npm start

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-admin-iKy@2.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-admin-iKy@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T11_08_37_849Z-debug.log

**Comment by KennBro** [comment]
SO? NodeJS version? npm version?
Do you execute npm install previously?

**Comment by Strannik74** [comment]
Good evening!
Remembered!
npm update
npm run build
Compiles!
Everything is fine!
Thanks!
![photoeditorsdk-export](https://user-images.githubusercontent.com/31668854/85166904-69932e00-b281-11ea-8742-e70a813aaf75.png)

**Comment by KennBro** [comment]
Great!!!
Regards

**Comment by Rajkumar-kumawat** [comment]
npm WARN ngx-admin-iKy@2.0.0 No description
npm WARN ngx-admin-iKy@2.0.0 No repository field.
