### ISSUE TITLE
API keys do not persist

### ISSUE THREAD

**Issue by Hax0rG1rl** [kennbroorg/iKy#2]
HI, 

**Issue:** I am trying to insert the API keys. Once all the fields get populated I am navigating away and I am trying to use the search option from the main page. 

I am getting an error like no API keys were defined. 

I am going back to the API key section and all the fields are voided / blank. 

Is there any trick here? I have not seen any save button and the current update option just pops us the option to re-edit the fields.

**OS:** Xubuntu 18.04 / nodejs v12

Thanks!

**Comment by KennBro** [comment]
Ok, I am going to make a video with the procedure. But, would you open one issue in the gitlab project with the same description? Please.
Regards
