### ISSUE TITLE
NPM INSTALL ERROR

### ISSUE THREAD

**Issue by INsanee112** [kennbroorg/iKy#21]
/iKy/frontend$ npm install
Violación de segmento- extract:regenerator-runtime: sill tarball no local

**Comment by KennBro** [comment]
Hi
What is the OS?
What is the node version?

**Comment by INsanee112** [comment]
Hi, thanks for answer.
Kali Linux 5.7.0
Node v10.21.0

**Comment by KennBro** [comment]
I recommend node 12 or higher
And if it's not too much trouble, let's close this issue and open it at https://gitlab.com/kennbroorg/iKy
Here is a link to an installation video in Kali 2020.02
https://www.youtube.com/watch?v=qJ_lGxuCC-U
