### ISSUE TITLE
ParrotOS issue

### ISSUE THREAD

**Issue by s1l3nt78** [kennbroorg/iKy#24]
Hey so i saw on gitlab the parrotOS issues and Ive been having this issue across my distros.

But here is a screenshot of the npm error thrown on Parrot & Kali
![Annotation 2020-08-26 193239](https://user-images.githubusercontent.com/44367179/91337021-11bdf980-e7d3-11ea-87e2-8c338e64b450.png)

**Comment by KennBro** [comment]
Hi
What is the nodeJS version?
Just keep in mind that Parrot OS comes with nodejs10 and npm is not installed. 
You can download NodeJS 12
```
wget https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
tar xvf node-v12.18.3-linux-x64.tar.xz
```
And export PATH with the nodejs12 bin directory preceding the previous PATH, like this
```
export PATH=/home/user/nodejs12dir/bin:$PATH
```
Then, in the same terminal, and inside frontend directory of iKy run
```
npm install
npm start
```

**Comment by s1l3nt78** [comment]
I did try with nodeJS 12 but ill purge it try again with a fresh node install and let you know

**Comment by KennBro** [comment]
You only need to delete the node_module directory under frontend and run 
```
npm install
npm start
```

**Comment by s1l3nt78** [comment]
Okay will do,
and i noticed the docker version installs and tried to run node10
