### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Strannik74** [kennbroorg/iKy#25]
Good evening!
An error occured
![Снимок экрана от 2020-08-30 20-24-47](https://user-images.githubusercontent.com/31668854/91662969-43023680-eaff-11ea-9a1c-6a0c91b6d0dc.png)

**Comment by Strannik74** [comment]
Good evening!
Couldn't fix the error. On another PC, I put everything started, but again the error there are no fields for entering API keys
Kali Linux 2020
![Снимок экрана от 2020-09-02 16-35-20](https://user-images.githubusercontent.com/31668854/91976647-b774e980-ed3a-11ea-8f7b-8152434f7567.png)

**Comment by KennBro** [comment]
Hi.
I just push a fix. I forgot a comma. Thanks
