### ISSUE TITLE
problem with start nmp

### ISSUE THREAD

**Issue by shanow7** [kennbroorg/iKy#27]
hi, can you help?

![image](https://user-images.githubusercontent.com/37192410/95076279-e0a9e080-0711-11eb-9d55-36a12cb4cf30.png)

**Comment by KennBro** [comment]
Please, send me logs of "npm install"

**Comment by shanow7** [comment]
npm install
npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.1001.4 requires a peer of typescript@>=3.9 < 4.1 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@10.1.4 requires a peer of @angular/compiler@10.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@10.1.4 requires a peer of typescript@>=3.9 <4.1 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/eva-icons@4.4.0 requires a peer of eva-icons@^1.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@10.1.4 requires a peer of typescript@>=3.9 < 4.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@7.0.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@7.0.0 requires a peer of @angular/compiler@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@7.0.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN jspdf-autotable@3.2.13 requires a peer of jspdf@^1.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.2 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.2 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.2 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-smart-table@1.3.5 requires a peer of @angular/common@^6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-smart-table@1.3.5 requires a peer of @angular/core@^6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-smart-table@1.3.5 requires a peer of @angular/forms@^6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-language-service@0.9.9 requires a peer of typescript@>= 2.3.1 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-admin-iKy@2.0.0 No description
npm WARN ngx-admin-iKy@2.0.0 No repository field.

audited 2854 packages in 17.611s

118 packages are looking for funding
  run `npm fund` for details

found 183 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by KennBro** [comment]
Ok, everything is fine. Just try 
```
npm start
```

**Comment by KennBro** [comment]
Check the new documentation about the installation without nodejs and angular.
https://github.com/kennbroorg/iKy#installation
