### ISSUE TITLE
error while running npm start

### ISSUE THREAD

**Issue by StarLord07** [kennbroorg/iKy#28]
there is an error while running npm start after the successful command of backend side (Redis-server | ./celery.sh | python3 app.py) after all, when I go for running frontend server, execute the following command from directory frontend

![Capture](https://user-images.githubusercontent.com/19605158/97771383-46975580-1b62-11eb-86f6-7e7e75e3afba.JPG)

here is a screenshot, of error 

saved log : 

0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]

1 info using npm@7.0.3

2 info using node@v15.0.1

3 timing config:load:defaults Completed in 2ms

4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms

5 timing config:load:builtin Completed in 1ms

6 timing config:load:cli Completed in 2ms

7 timing config:load:env Completed in 0ms

8 timing config:load:file:/home/kali/Tools/iKy/frontend/.npmrc Completed in 0ms

9 timing config:load:project Completed in 1ms

10 timing config:load:file:/home/kali/.npmrc Completed in 0ms

11 timing config:load:user Completed in 0ms

12 timing config:load:file:/usr/etc/npmrc Completed in 1ms

13 timing config:load:global Completed in 1ms

14 timing config:load:cafile Completed in 0ms

15 timing config:load:validate Completed in 0ms

16 timing config:load:setUserAgent Completed in 0ms

17 timing config:load:setEnvs Completed in 0ms

18 timing config:load Completed in 8ms

19 verbose npm-session d274ceca2b2c717b

20 timing npm:load Completed in 18ms

21 timing command:run-script Completed in 9ms

22 timing command:start Completed in 12ms

23 verbose stack Error: command failed

23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)

23 verbose stack     at ChildProcess.emit (node:events:327:20)

23 verbose stack     at maybeClose (node:internal/child_process:1048:16)

23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)

24 verbose pkgid ngx-admin-iKy@2.0.0

25 verbose cwd /home/kali/Tools/iKy/frontend

26 verbose Linux 5.5.0-kali2-amd64

27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"

28 verbose node v15.0.1

29 verbose npm  v7.0.3

30 error code 127

31 error path /home/kali/Tools/iKy/frontend

32 error command failed

33 error command sh -c ng serve

34 verbose exit 127

**Comment by KennBro** [comment]
Hi, inside frontend directory execute the following command :
```
npm install -g @angular/cli
```
and try again

**Comment by shanow7** [comment]
npm install -g @angular/cli
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osint/.npm/_logs/2020-11-08T20_32_39_439Z-debug.log

**Comment by KennBro** [comment]
sudo

**Comment by shanow7** [comment]
sudo npm install -g @angular/cli
[sudo] password for osint: 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 280 packages, and audited 280 packages in 16s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
osint@kali:~/OSINT/IKY/iKy/frontend$ sudo npm start

> ngx-admin-iKy@2.0.0 start
> ng serve

An unhandled exception occurred: Cannot read property 'Minus' of undefined
See "/tmp/ng-Jq7Svp/angular-errors.log" for further details.
npm ERR! code 127
npm ERR! path /home/osint/OSINT/IKY/iKy/frontend
npm ERR! command failed
npm ERR! command sh -c ng serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-09T16_25_11_793Z-debug.log

**Comment by vajjazled** [comment]
@shanow7 - Try the following in the frontend folder 
npm rm -rf node_modules
After that I ran npm start - works like a charm.

**Comment by KennBro** [comment]
@vajjazled thank for collaborate

**Comment by shanow7** [comment]
npm rm -rf node_modules

up to date, audited 2781 packages in 5s

1 package is looking for funding
  run `npm fund` for details

2 low severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
osint@kali:~/OSINT/IKY/iKy/frontend$ npm start

> ngx-admin-iKy@2.0.0 start
> ng serve

An unhandled exception occurred: Cannot read property 'Minus' of undefined
See "/tmp/ng-FWRqqa/angular-errors.log" for further details.
npm ERR! code 127
npm ERR! path /home/osint/OSINT/IKY/iKy/frontend
npm ERR! command failed
npm ERR! command sh -c ng serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osint/.npm/_logs/2020-11-12T21_23_10_100Z-debug.log
osint@kali:~/OSINT/IKY/iKy/frontend$ sudo npm rm -rf node_modules
[sudo] password for osint: 

up to date, audited 2781 packages in 5s

1 package is looking for funding
  run `npm fund` for details

2 low severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
osint@kali:~/OSINT/IKY/iKy/frontend$ npm fund
ngx-admin-iKy@2.0.0
└── https://github.com/sponsors/epoberezkin
    └── ajv@6.12.4

osint@kali:~/OSINT/IKY/iKy/frontend$ npm audit fix
npm WARN audit fix minimist@0.0.8 node_modules/live-server/node_modules/fsevents/node_modules/minimist
npm WARN audit fix minimist@0.0.8 is a bundled dependency of
npm WARN audit fix minimist@0.0.8 fsevents@1.2.11 at node_modules/live-server/node_modules/fsevents
npm WARN audit fix minimist@0.0.8 It cannot be fixed automatically.
npm WARN audit fix minimist@0.0.8 Check for updates to the fsevents package.
npm WARN audit fix minimist@1.2.0 node_modules/live-server/node_modules/fsevents/node_modules/rc/node_modules/minimist
npm WARN audit fix minimist@1.2.0 is a bundled dependency of
npm WARN audit fix minimist@1.2.0 fsevents@1.2.11 at node_modules/live-server/node_modules/fsevents
npm WARN audit fix minimist@1.2.0 It cannot be fixed automatically.
npm WARN audit fix minimist@1.2.0 Check for updates to the fsevents package.
npm WARN audit fix mkdirp@0.5.1 node_modules/live-server/node_modules/fsevents/node_modules/mkdirp
npm WARN audit fix mkdirp@0.5.1 is a bundled dependency of
npm WARN audit fix mkdirp@0.5.1 fsevents@1.2.11 at node_modules/live-server/node_modules/fsevents
npm WARN audit fix mkdirp@0.5.1 It cannot be fixed automatically.
npm WARN audit fix mkdirp@0.5.1 Check for updates to the fsevents package.

up to date, audited 2781 packages in 6s

1 package is looking for funding
  run `npm fund` for details

# npm audit report

minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
fix available via `npm audit fix`
node_modules/live-server/node_modules/fsevents/node_modules/minimist
node_modules/live-server/node_modules/fsevents/node_modules/rc/node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/live-server/node_modules/fsevents/node_modules/mkdirp

2 low severity vulnerabilities

To address all issues, run:
  npm audit fix
osint@kali:~/OSINT/IKY/iKy/frontend$ npm start

> ngx-admin-iKy@2.0.0 start
> ng serve

An unhandled exception occurred: Cannot read property 'Minus' of undefined
See "/tmp/ng-OQL0u8/angular-errors.log" for further details.
npm ERR! code 127
npm ERR! path /home/osint/OSINT/IKY/iKy/frontend
npm ERR! command failed
npm ERR! command sh -c ng serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osint/.npm/_logs/2020-11-12T21_25_51_761Z-debug.log

**Comment by KennBro** [comment]
Check the new documentation about the installation without nodejs and angular.
https://github.com/kennbroorg/iKy#installation

**Comment by aerhix** [comment]
![imagen_2021-05-10_220050](https://user-images.githubusercontent.com/83999138/117760823-2e705500-b1db-11eb-96eb-ca6c83c4dff2.png)

I have not been able to solve this, why is it?
