### ISSUE TITLE
e

### ISSUE THREAD

**Issue by tobi437a** [kennbroorg/iKy#31]
e

**Comment by KennBro** [comment]
This issue is out of scope, but...
When you say you are using a Kali Linux Terminal inside Windows 10, Are you using WSL or virtual machine?

**Comment by tobi437a** [comment]
WSL

**Comment by KennBro** [comment]
Please send me a screenshot with the output of following commands :
```shell
ls
unzip iKy.zip
```

**Comment by tobi437a** [comment]
Update: I tried to do it again the exact same way, and it's working now
