### ISSUE TITLE
problema al iniciar npm start

### ISSUE THREAD

**Issue by trevanyam** [kennbroorg/iKy#38]
Hola 

Tengo el siguiente error al ejecutar el comando npm start. lo scomandos previos de front end y redis no presentan problema 

root@kali:~/tools/iKy/frontend# npm run build

> ngx-admin-iKy@2.0.0 build /root/tools/iKy/frontend
> ng build

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(rebaseRootRelativeCssUrls).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-admin-iKy@2.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-admin-iKy@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-09T14_48_24_539Z-debug.log
root@kali:~/tools/iKy/frontend# 

Intente solucionarlo ejecutando previamente los comandos 
npm update 
npm run build 

pero genera el siguiente error en el build

root@kali:~/tools/iKy/frontend# npm run build

> ngx-admin-iKy@2.0.0 build /root/tools/iKy/frontend
> ng build

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(rebaseRootRelativeCssUrls).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-admin-iKy@2.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-admin-iKy@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-09T14_41_59_446Z-debug.log

Las versiones de node y el npm son
node v14.15.4
npm 6.14.10

Espero que pueda ayudarme, gracias!

**Comment by KennBro** [comment]
Puede instalar el pack para no tener que lidiar con node. 

https://gitlab.com/kennbroorg/iKy#installation

Para determinar el error en npm start necesito el log completo.

**Comment by KennBro** [comment]
Reabra el issue si es necesario
