### ISSUE TITLE
Error Start front-end app

### ISSUE THREAD

**Issue by daniel2005d** [kennbroorg/iKy#45]
I followed the wiki steps.

1. Install and Compile redis
2. unzip inky zip file
3. install python requierements
4. Start app 

When i try browse http://localhost:4200, on the developper console show the ERROR Error: Uncaught (in promise): TypeError: jsPDF.API is undefined error. 

And just showme IkY logo.

![2021-02-18_17-44](https://user-images.githubusercontent.com/9272841/108431470-e7dd1100-7210-11eb-903d-6f7d0726f0d0.png)

**Comment by KennBro** [comment]
Sorry for the delay, I was on holiday.
This was fixed. Update please.

**Comment by daniel2005d** [comment]
Gracias. It's works . Funciono

**Comment by KennBro** [comment]
Jajaja. English or Español?
