### ISSUE TITLE
NOW SHOWING DATA AND GRAPHS 

### ISSUE THREAD

**Issue by kamdar3** [kennbroorg/iKy#49]
I searched my Instagram username it not now showing any data and state is stucked on process for 45min and nor processing further

![IMG_20210403_140751913](https://user-images.githubusercontent.com/57684027/113473838-b8fdc000-9489-11eb-824e-64f31c0d4ba0.jpg)
![IMG_20210403_140729320](https://user-images.githubusercontent.com/57684027/113473841-bd29dd80-9489-11eb-8d7e-25543062ead7.jpg)

**Comment by KennBro** [comment]
I need the celery logs

**Comment by kamdar3** [comment]
Showing error in npm log and see celery 

![IMG_20210407_112159_569](https://user-images.githubusercontent.com/57684027/113817774-79d6b400-9794-11eb-8eba-e26b9ecf6edf.jpg)

**Comment by kamdar3** [comment]
![IMG_20210407_112141_863](https://user-images.githubusercontent.com/57684027/113818001-c6ba8a80-9794-11eb-9ad9-230b00824fda.jpg)

**Comment by kamdar3** [comment]
celery log is above

**Comment by KennBro** [comment]
No, celery log is very long. Please send me the log, no screenshot

**Comment by KennBro** [comment]
Due to the time elapsed without response, I close the issue. Feel free to reopen it
