### ISSUE TITLE
celery  update 

### ISSUE THREAD

**Issue by Rajkumar-kumawat** [kennbroorg/iKy#51]
You are using `--app` as an option of the worker sub-command:                                                     
celery worker --app celeryapp <...>                      
                                                         
The support for this usage was removed in Celery 5.0. Instead you should use `--app` as a global option:          
celery --app celeryapp worker <...>                      
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: no such option: --app

**Comment by Rajkumar-kumawat** [comment]
please resole

**Comment by KennBro** [comment]
In a terminal run 
```
pip install celery==4.4.5
```

**Comment by Rajkumar-kumawat** [comment]
okay done thanku it run
