### ISSUE TITLE
｢wds｣: webpack output is served from / ℹ ｢wds｣: 404s will fallback to //index.html

### ISSUE THREAD

**Issue by Rajkumar-kumawat** [kennbroorg/iKy#52]
｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

**Comment by KennBro** [comment]
Sorry, I need the whole log

**Comment by wasim-chadhar** [comment]
10:34:12 PM - Found 0 errors. Watching for file changes.
app listening at http://localhost:3001
MongoDB connected
i ｢wds｣: Project is running at http://10.75.23.106/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from E:\FYP\CWC-B2B\frontend\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

Facing this issue ?  need help how to resolve
