### ISSUE TITLE
Installation completed but no results

### ISSUE THREAD

**Issue by a4j4123** [kennbroorg/iKy#6]
The system is installed, but the search mailbox does not show any results.
![cdd](https://user-images.githubusercontent.com/22828636/68468151-68f9da00-0252-11ea-9ac0-c77063387a00.JPG)

**Comment by SWarrior97** [comment]
i have the same problem

**Comment by shanow7** [comment]
which installation is correct:
https://www.youtube.com/watch?v=R1exaRDLuBQ&t=356s
or
https://github.com/kennbroorg/iKy

**Comment by KennBro** [comment]
Sorry for the delay, but the project is in gitlab, this is just a mirror.
This is the project link
https://gitlab.com/kennbroorg/iKy
I also leave the wiki link
https://gitlab.com/kennbroorg/iKy/-/wikis/home

Sorry for the delay again
Regards
Kennbro

PD: If you still have problems, please open the issue on gitlab
