### ISSUE TITLE
La aplicación funciona bien en localhost, pero no puedo verla desde otra maquina.-

### ISSUE THREAD

**Issue by theinventor1972** [kennbroorg/iKy#61]
Hola kennbroo.  
  Logré instalar la aplicación en un kali64 bits, y quedó andando perfecto. 
  Pero al navegar desde otro PC, no logro que realice las búsquedas, ni tampoco puedo ver las API Keys... me di cuenta que el tema puede estar en el Flask. Entonces hice lo siguiente: 
 1.- cambiar las IP por '0.0.0.0' en el  archivo /Iky/backend/app.py , en donde estaban las instancias del flask, lo máximo que logré fué que el 'curl' me respondiera las 'tasklist' desde otra maquina en la red, pero en el aplicativo, no realiza búsquedas ni puedo ver las API Keys... pero el curl si me responde... creo que estoy cerca.
![Captura de pantalla de 2021-06-18 02-54-45](https://user-images.githubusercontent.com/86097393/122520151-4197f100-cfe1-11eb-9023-5e828a3fb451.png)

  se agradece alguna pista desde ya.

Slds. desde Chile.

**Comment by KennBro** [comment]
Esta herramienta no está pensada para correrla desde distintos hosts. Hay maneras pero no las recomiendo por motivos de seguridad.
