### ISSUE TITLE
Problem with python

### ISSUE THREAD

**Issue by scotland95** [kennbroorg/iKy#62]
Hi,
i have a problem with finally installation:

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from factories.application import create_application
  File "/home/dscozia/iKy-pack/backend/factories/application.py", line 2, in <module>
    from flask import Flask

could you help me please?

**Comment by KennBro** [comment]
I need information about the operating system and version of python you are running.
You are probably mixing environments or python versions.

**Comment by scotland95** [comment]
yes 👍 , i' m using 
Ubuntu 21.04 
Python 3.9.5

**Comment by KennBro** [comment]
Could you send me a screenshot of the command you are running?

**Comment by KennBro** [comment]
Given the time elapsed I close the issue. If you need reopen it
