### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by Archviz360** [kennbroorg/iKy#64]
when im starting i came to the logo but that's it. it loops without starting the software.

**Comment by KennBro** [comment]
Please give me more info. SO, python version, iinstallation type, npm if applicable, logs, etc.

**Comment by Archviz360** [comment]
i tried to reinstall everything after doing a factory reset of my pc and now when i install reqirements after installing latest python i get this error 

ERROR: Command errored out with exit status 1: command: 'C:\Users\dacia\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\dacia\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\dacia\AppData\Local\Temp\tmp7hu8g5me' cwd: C:\Users\dacia\AppData\Local\Temp\pip-install-7fotlzia\multidict_fb5cafd4670c4424a7e84154f4082699 Complete output (41 lines): ********************** * Accellerated build * ********************** running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-3.9 creating build\lib.win-amd64-3.9\multidict copying multidict\_abc.py -> build\lib.win-amd64-3.9\multidict copying multidict\_compat.py -> build\lib.win-amd64-3.9\multidict copying multidict\_multidict_base.py -> build\lib.win-amd64-3.9\multidict copying multidict\_multidict_py.py -> build\lib.win-amd64-3.9\multidict copying multidict\__init__.py -> build\lib.win-amd64-3.9\multidict running egg_info writing multidict.egg-info\PKG-INFO writing dependency_links to multidict.egg-info\dependency_links.txt writing top-level names to multidict.egg-info\top_level.txt reading manifest file 'multidict.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no previously-included files matching '*.pyc' found anywhere in distribution warning: no previously-included files found matching 'multidict\_multidict.html' warning: no previously-included files found matching 'multidict\*.so' warning: no previously-included files found matching 'multidict\*.pyd' warning: no previously-included files found matching 'multidict\*.pyd' no previously-included directories found matching 'docs\_build' adding license file 'LICENSE' writing manifest file 'multidict.egg-info\SOURCES.txt' copying multidict\__init__.pyi -> build\lib.win-amd64-3.9\multidict copying multidict\_multidict.c -> build\lib.win-amd64-3.9\multidict copying multidict\py.typed -> build\lib.win-amd64-3.9\multidict creating build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\defs.h -> build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\dict.h -> build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\istr.h -> build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\iter.h -> build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\pair_list.h -> build\lib.win-amd64-3.9\multidict\_multilib copying multidict\_multilib\views.h -> build\lib.win-amd64-3.9\multidict\_multilib running build_ext building 'multidict._multidict' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ ---------------------------------------- ERROR: Failed building wheel for multidict

can it be because i haven't installed VisualStudio code yet??

**Comment by KennBro** [comment]
Please give me more info. Operating System, python version, iinstallation type, npm if applicable, logs, etc.
iKy don't work in windows native.

**Comment by KennBro** [comment]
Given the time elapsed I close the issue. If you need reopen it
