### ISSUE TITLE
easy installation problem

### ISSUE THREAD

**Issue by shanow7** [kennbroorg/iKy#7]
hi, I've try to install but I heve 
 
![image](https://user-images.githubusercontent.com/37192410/72474644-8797c680-37e9-11ea-9cbe-aaf186913758.png)

what I'm doing wrong?

**Comment by KennBro** [comment]
Hello, iKy Easy Install is an experiment and I should work more on that. Currently it only supports ubuntu 18.04.

But instead of running ./iKyEasyInstall.sh, please run inside install/iKyEasyInstall

`bash scripts/ubuntu1804.sh`

And let me know if it works to add Kali as a supported distribution

Regards and thanks
KennBro

**Comment by shanow7** [comment]
I've this

![image](https://user-images.githubusercontent.com/37192410/73004358-719c8e00-3e07-11ea-9959-713364e76127.png)

**Comment by KennBro** [comment]
The last error will be corrected by running 
`sudo apt-get install -y npm`

But the mistake that worries me is the one in red. Could you send me previous messages?

**Comment by shanow7** [comment]
I've thisTemat: Re: [kennbroorg/iKy] easy installation problem (#7)Data: 2020-01-23 17:53Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; The last error will be corrected by runningsudo apt-get install -y npm
But the mistake that worries me is the one in red. Could you send me previous messages?

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)

my email: shanow@interia.pl

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/73008676-59307180-3e0f-11ea-95b7-f80beb0e5fc4.png)

**Comment by KennBro** [comment]
> ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> 
> my email: [shanow@interia.pl](mailto:shanow@interia.pl)

Here the solution for this error that was generated as a side effect
`
sudo apt update
sudo apt install --fix-missing
`

**Comment by KennBro** [comment]
> ![image](https://user-images.githubusercontent.com/37192410/73008676-59307180-3e0f-11ea-95b7-f80beb0e5fc4.png)

This error occurs because development libraries are missing. Please run this 

`
sudo apt install libxslt1-dev libxml2-dev libxslt-dev
`

**Comment by shanow7** [comment]
> > ![image](https://user-images.githubusercontent.com/37192410/73008676-59307180-3e0f-11ea-95b7-f80beb0e5fc4.png)
> 
> This error occurs because development libraries are missing. Please run this
> 
> `sudo apt install libxslt1-dev libxml2-dev libxslt-dev`

it's ok :)

**Comment by shanow7** [comment]
> > ![image](https://user-images.githubusercontent.com/37192410/73008676-59307180-3e0f-11ea-95b7-f80beb0e5fc4.png)
> 
> This error occurs because development libraries are missing. Please run this
> 
> `sudo apt install libxslt1-dev libxml2-dev libxslt-dev`

![image](https://user-images.githubusercontent.com/37192410/73017481-35c1f280-3e20-11ea-97ab-75525d0777ea.png)

**Comment by shanow7** [comment]
> > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> 
> Here the solution for this error that was generated as a side effect
> `sudo apt update sudo apt install --fix-missing`

![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)

**Comment by KennBro** [comment]
> > > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> > 
> > 
> > Here the solution for this error that was generated as a side effect
> > `sudo apt update sudo apt install --fix-missing`
> 
> ![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)

`sudo apt update `
`sudo apt install --fix-missing`

**Comment by shanow7** [comment]
my email: shanow@interia.pl

Here the solution for this error that was generated as a side effectsudo apt update sudo apt install --fix-missing



sudo apt update  sudo apt install --fix-missing

**Comment by shanow7** [comment]
> > > > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > > > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> > > 
> > > 
> > > Here the solution for this error that was generated as a side effect
> > > `sudo apt update sudo apt install --fix-missing`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)
> 
> `sudo apt update `
> `sudo apt install --fix-missing`

![image](https://user-images.githubusercontent.com/37192410/73081446-ea631f00-3ec7-11ea-9d48-489557ce5c2f.png)

**Comment by KennBro** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > > > > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> > > > 
> > > > 
> > > > Here the solution for this error that was generated as a side effect
> > > > `sudo apt update sudo apt install --fix-missing`
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)
> > 
> > 
> > `sudo apt update `
> > `sudo apt install --fix-missing`
> 
> ![image](https://user-images.githubusercontent.com/37192410/73081446-ea631f00-3ec7-11ea-9d48-489557ce5c2f.png)

They are two different commands.

A command is `sudo apt update`
And the other command is `sudo apt install --fix-missing`

**Comment by shanow7** [comment]
I know, how you see I had use those but nothing was change, any idea?Temat: Re: [kennbroorg/iKy] easy installation problem (#7)Data: 2020-01-24 17:21Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 





my email: shanow@interia.pl

Here the solution for this error that was generated as a side effectsudo apt update sudo apt install --fix-missing



sudo apt update sudo apt install --fix-missing



They are two different commands.
A command is sudo apt update
And the other command is sudo apt install --fix-missing

**Comment by shanow7** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > > > > > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> > > > > 
> > > > > 
> > > > > Here the solution for this error that was generated as a side effect
> > > > > `sudo apt update sudo apt install --fix-missing`
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)
> > > 
> > > 
> > > `sudo apt update `
> > > `sudo apt install --fix-missing`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37192410/73081446-ea631f00-3ec7-11ea-9d48-489557ce5c2f.png)
> 
> They are two different commands.
> 
> A command is `sudo apt update`
> And the other command is `sudo apt install --fix-missing`

nothing was change

![image](https://user-images.githubusercontent.com/37192410/73137634-9177c000-405a-11ea-8fdb-fdd9115797bf.png)

**Comment by shanow7** [comment]
nothing change, any idea?Temat: Re: [kennbroorg/iKy] easy installation problem (#7)Data: 2020-01-24 17:21Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "shanow7" ; "Author" ; 





my email: shanow@interia.pl

Here the solution for this error that was generated as a side effectsudo apt update sudo apt install --fix-missing



sudo apt update sudo apt install --fix-missing



They are two different commands.
A command is sudo apt update
And the other command is sudo apt install --fix-missing

**Comment by shanow7** [comment]
when I use a normal install I've problem with command ./celery.sh

![image](https://user-images.githubusercontent.com/37192410/73139129-0ce16d80-406b-11ea-8b4f-e7672a945188.png)

**Comment by KennBro** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/37192410/73008422-d3acc180-3e0e-11ea-91d7-cd0c59c7594e.png)
> > > > > > > my email: [shanow@interia.pl](mailto:shanow@interia.pl)
> > > > > > 
> > > > > > 
> > > > > > Here the solution for this error that was generated as a side effect
> > > > > > `sudo apt update sudo apt install --fix-missing`
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/37192410/73017620-728de980-3e20-11ea-9d84-a8ed1913e431.png)
> > > > 
> > > > 
> > > > `sudo apt update `
> > > > `sudo apt install --fix-missing`
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/37192410/73081446-ea631f00-3ec7-11ea-9d48-489557ce5c2f.png)
> > 
> > 
> > They are two different commands.
> > A command is `sudo apt update`
> > And the other command is `sudo apt install --fix-missing`
> 
> nothing was change
> 
> ![image](https://user-images.githubusercontent.com/37192410/73137634-9177c000-405a-11ea-8fdb-fdd9115797bf.png)

Yes, that changed. The messages are different. I don't know what version of Kali you are using, but it has a problem with repositories that are unrelated to iKy.
However, I have a question. Did you run this command?

`sudo apt-get install -y npm`

As I mentioned in the https://github.com/kennbroorg/iKy/issues/7#issuecomment-577770113

**Comment by KennBro** [comment]
> when I use a normal install I've problem with command ./celery.sh
> 
> ![image](https://user-images.githubusercontent.com/37192410/73139129-0ce16d80-406b-11ea-8b4f-e7672a945188.png)

This is Parrot and you are mixing errors. Let's continue with Kali. But...
Could you run this command inside iKy directory and send me the output?

`python3.7 -m pip install -r requirements.txt`

**Comment by shanow7** [comment]
> Yes, that changed. The messages are different. I don't know what version of Kali you are using, but it has a problem with repositories that are unrelated to iKy.
> However, I have a question. Did you run this command?

I did, I've Kali Linux 2019.4 amd64 2.6GB

**Comment by KennBro** [comment]
> > Yes, that changed. The messages are different. I don't know what version of Kali you are using, but it has a problem with repositories that are unrelated to iKy.
> > However, I have a question. Did you run this command?
> 
> I did, I've Kali Linux 2019.4 amd64 2.6GB

But the error in the screenshot is that there is no "npm" command. And that is installed with

`sudo apt-get install -y npm`

**Comment by shanow7** [comment]
I use&nbsp;sudo apt-get install -y npmthen I use sudo apt updatesudo apt install --fix-missing

Yes, that changed. The messages are different. I don't know what version of Kali you are using, but it has a problem with repositories that are unrelated to iKy.
However, I have a question. Did you run this command?

I did, I've Kali Linux 2019.4 amd64 2.6GB

But the error in the screenshot is that there is no "npm" command. And that is installed with
sudo apt-get install -y npm

**Comment by shanow7** [comment]
hi, I try in new kali linux instalation but I've problem
![image](https://user-images.githubusercontent.com/37192410/74773055-70894000-5291-11ea-8953-95e699f8b7ab.png)

**Comment by KennBro** [comment]
I don't understand where the error comes from
