### ISSUE TITLE
Issue with npm, both manually and with easy install

### ISSUE THREAD

**Issue by Criceratops** [kennbroorg/iKy#75]
Hello guys, i have used the easyinstall script and the dev version with different npm and nodejs versions but i keep failing on the npm initialization. It appears to exist a problem with http_parser in the current version. Do you recomend another npm or nodejs version?

This is the error:

> ngx-admin-iKy@2.0.0 start
> ng serve

(node:2603521) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at NormalModule._initBuildHash (~/Tools/iKy/frontend/node_modules/webpack/lib/NormalModule.js:412:16)
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0

**Comment by KennBro** [comment]
Try with this link (https://gitlab.com/kennbroorg/iKy#easy-installation-python-only). 
This avoid you to install node and npm
