### ISSUE TITLE
Problem with backend

### ISSUE THREAD

**Issue by robertoceb** [kennbroorg/iKy#77]
In Easy installation (Python only) when execute this part 
python app.py -e prod
i have this error in command line

┌──(root💀kali)-[/home/rober/iKy/backend]
└─# python3 app.py -e prod                                                  1 ⨯
Traceback (most recent call last):
  File "/home/rober/iKy/backend/app.py", line 2, in <module>
    from factories.application import create_application
  File "/home/rober/iKy/backend/factories/application.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)

Can you help me??
Thanks

**Comment by KennBro** [comment]
I use python 3.9 
Could you tell me the version of flask?
Run this command
`
pip freeze | grep flask
`

**Comment by robertoceb** [comment]
sorry for delay this is result
┌──(root💀kali)-[/home/rober/iKy]
└─# pip freeze | grep flask
                                                                                
┌──(root💀kali)-[/home/rober/iKy]
└─#                                                                         1 ⨯

**Comment by KennBro** [comment]
I must update the package dependencies.
In the meantime, try with this
```
pip install Flask=2.1.0
```

**Comment by KennBro** [comment]
Fixed on 1255a8835f29a2a2a28b9da38af0a61a3b636141
