### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by miskly** [kennbroorg/iKy#89]
Hi,

I have an error when im running a npm  start when im in the iKy>frontend file

the error is : DEPRECATED  : The 'default project' workspace option has been deprecated. The project to use will be determined from the current working directory. 

Error : could not find the '@angulardevkit/build-angular:dev-server' builder's node package.

However, when i run the install nodejs command line its says that nodejs is already the newest version.

Can you help me please? Thank you :) And have a great day

**Comment by KennBro** [comment]
Install node, etc, is for developers. Try easy installation (Only Python)
https://github.com/kennbroorg/iKy#installation
