### ISSUE TITLE
Can't update API Key

### ISSUE THREAD

**Issue by jibbysquare** [kennbroorg/iKy#93]
Hi, love the interface, well done! but I can't update the API keys, and I think this is why when I try to search for a target, nothing happens, is that right? I hit enter and nothing changes? Can you help please

**Comment by KennBro** [comment]
If you can't update API keys something is wrong. Try this https://twitter.com/kennbroorg/status/1281204454851665920?s=20&t=WRZJRUmWw-2kEK-6TtbBsg
