### ISSUE TITLE
Report question

### ISSUE THREAD

**Issue by shadowdevnotreal** [kennbroorg/iKy#94]
Not a problem per say.
The beautiful graphs that come up after the scan is done, how do I get those printed out?
Also the same with the profile section.

I do not see them in the reports that are generated.
I have tried to print the page as PDF and it does not work.
I have tried fireshot and nimbus, and that doesnt work.

When I do get a screen shot to work, there are lines in the page that show on each page break, but it isnt now viewable for share.
This application is amazing, but I cannot see how to get those graphs to a printed format.
Is there a way to export the sections like lets say the hohele maps?

It would be amazing to be able to export out selected sections of the scan, or the scan in the exact format it shows after running the scan itself.

Much appreciated for this amazing tool!!!!!

**Comment by KennBro** [comment]
The profile section does not appear graphically in the report because of the way I am exporting the graphs. Only data tables appear.
I need to check all the reporting, the graphs on the gather screen should be fine. But it is a very consuming process to build the report.
I am thinking of including a report without graphs and one with graphs. And I like the idea of selecting what to print.

Thanks for your words of encouragement!!!!!

**Comment by shadowdevnotreal** [comment]
Im am curious about what is doing the correlations of the data on the profile page.
I have been testing numerous algo and have not found one i like.
Yes, I have to increase the memory of my VM to run a report......usually crashes, but when successful.......takes a long time.
Would be amazing to export just graphs themselves, tables etc.
Like manually build a sectional report or the whole thing.
Then again I am a crappy developer, and more of an idea person.
I will make sure to update my pull and test again if you have made any new changes.
This app is amazing!!!!! Would be great to be able to customize the report, which I am sure it can be.
Can you guide me on how to add custom logo to the report?

**Comment by KennBro** [comment]
Sorry for the delay in answering. Render the graphs in high consume process. I actually working on that, but it always be a high consumer process. 
I'm thinking about select between a report with only tables and data, and a report including graphs

**Comment by KennBro** [comment]
The report is working with all the graphs
