### ISSUE TITLE
Error al iniciar npm en Frontend

### ISSUE THREAD

**Issue by ManuelBot59** [kennbroorg/iKy#99]
Hola keenbrog, tengo un problema, eh seguido todos los pasos que se menciona, pero al momento de querer iniciar el npm start en la carpeta frontend me sale el siguiente error:

`┌──(root㉿manuelxx)-[/home/anony590/iKy/frontend]
`└─# npm start

`> ngx-admin-iKy@2.0.0 start
`> ng serve

`10% building 3/3 modules 0 active(node:3218) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is `deprecated.                  
`(Use `node --trace-deprecation ...` to show where the warning was created)
`ℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
`ℹ ｢wds｣: webpack output is served from /
`ℹ ｢wds｣: 404s will fallback to //index.html
`10% building 3/4 modules 1 active ...:0/sockjs-node&sockPath=/sockjs-nodenode:internal/crypto/hash:71
 ` this[kHandle] = new _Hash(algorithm, xofLen);
  `                ^

`Error: error:0308010C:digital envelope routines::unsupported
 `   at new Hash (node:internal/crypto/hash:71:19)
  `  at Object.createHash (node:crypto:133:10)
   ` at module.exports (/home/anony590/iKy/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    `at NormalModule._initBuildHash (/home/anony590/iKy/frontend/node_modules/webpack/lib/NormalModule.js:412:16)
   ` at /home/anony590/iKy/frontend/node_modules/webpack/lib/NormalModule.js:444:10
`    at /home/anony590/iKy/frontend/node_modules/webpack/lib/NormalModule.js:320:13
 `   at /home/anony590/iKy/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
 `   at /home/anony590/iKy/frontend/node_modules/loader-runner/lib/LoaderRunner.js:203:19
 `   at VirtualFileSystemDecorator.readFile `(/home/anony590/iKy/frontend/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:46:13)
`    at processResource (/home/anony590/iKy/frontend/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
 `   at iteratePitchingLoaders (/home/anony590/iKy/frontend/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
 `   at runLoaders (/home/anony590/iKy/frontend/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
 `   at NormalModule.doBuild (/home/anony590/iKy/frontend/node_modules/webpack/lib/NormalModule.js:292:3)
 `   at NormalModule.build (/home/anony590/iKy/frontend/node_modules/webpack/lib/NormalModule.js:438:15)
 `   at Compilation.buildModule (/home/anony590/iKy/frontend/node_modules/webpack/lib/Compilation.js:702:10)
 `   at /home/anony590/iKy/frontend/node_modules/webpack/lib/Compilation.js:944:14 {
 ` opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],                                                          
 ` library: 'digital envelope routines',
 ` reason: 'unsupported',
 ` code: 'ERR_OSSL_EVP_UNSUPPORTED'
`}

`Node.js v18.10.0

Espero puedas ayudarme por favor. Gracias, excelente su herramienta.

**Comment by KennBro** [comment]
Realmente necesita la instalación completa? Easy Installation (Only python) no le sirve? Y con eso se ahorra todo lo que tiene que ver con node...

**Comment by ManuelBot59** [comment]
lo tomaré en cuenta Keen, pude solucionar justamente con esa instalación facil. Muchas gracias, lo usaré para una exposición. Un gusto, en unos dias usaré su herramienta para un #VideoOsint publicado en mi twitter. Un gusto!
